services:
  - type: web
    name: hiresense-backend
    env: python
    region: ohio
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hiresense-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: hiresense-db
    databaseName: hiresense
    user: postgres
    region: ohio
    plan: free
