from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import Any, List
import uuid

from app.dependencies.db import get_db
from app.dependencies.auth import get_current_active_user
from app.models.recruiter import Recruiter
from app.schemas.analytics import ReportOut
from app.models.report import Report

router = APIRouter()

@router.get("", response_model=List[ReportOut])
def get_reports(
    skip: int = 0,
    limit: int = 100,
    db: Session = Depends(get_db),
    current_user: Recruiter = Depends(get_current_active_user),
) -> Any:
    """Retrieve all generated reports."""
    return db.query(Report).filter(Report.recruiter_id == current_user.id).offset(skip).limit(limit).all()

@router.post("/generate")
def generate_report(
    report_type: str = "Executive Summary",
    db: Session = Depends(get_db),
    current_user: Recruiter = Depends(get_current_active_user),
):
    """Dynamically generate a new report."""
    # In a real app, this would use the AnalyticsEngine and potentially an LLM to generate the report body
    
    report = Report(
        recruiter_id=current_user.id,
        title=f"{report_type} - {uuid.uuid4().hex[:6].upper()}",
        report_type=report_type,
        file_path=f"/reports/{uuid.uuid4().hex}.pdf"
    )
    db.add(report)
    db.commit()
    db.refresh(report)
    
    return report

@router.get("/{report_id}", response_model=ReportOut)
def get_report(
    report_id: int,
    db: Session = Depends(get_db),
    current_user: Recruiter = Depends(get_current_active_user),
):
    """Get specific report details."""
    report = db.query(Report).filter(Report.id == report_id, Report.recruiter_id == current_user.id).first()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
    return report

@router.delete("/{report_id}")
def delete_report(
    report_id: int,
    db: Session = Depends(get_db),
    current_user: Recruiter = Depends(get_current_active_user),
):
    """Delete a report."""
    report = db.query(Report).filter(Report.id == report_id, Report.recruiter_id == current_user.id).first()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
    db.delete(report)
    db.commit()
    return {"message": "Report deleted successfully"}

@router.get("/download/{report_id}")
def download_report(
    report_id: int,
    db: Session = Depends(get_db),
    current_user: Recruiter = Depends(get_current_active_user),
):
    """Download a generated report as a PDF."""
    from fastapi import Response
    from fpdf import FPDF
    
    report = db.query(Report).filter(Report.id == report_id, Report.recruiter_id == current_user.id).first()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
        
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=16)
    pdf.cell(200, 10, txt=report.title, ln=True, align='C')
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Type: {report.report_type}", ln=True)
    
    pdf.ln(10)
    pdf.multi_cell(0, 10, txt="This is an automated report generated by HireSense AI. It contains insights, rankings, and analytics based on your recruitment pipeline data.")
    
    pdf_bytes = pdf.output(dest='S').encode('latin-1')
    
    response = Response(content=pdf_bytes)
    response.headers["Content-Disposition"] = f"attachment; filename=report_{report_id}.pdf"
    response.headers["Content-Type"] = "application/pdf"
    return response
